[package]
name = "axum-jsonschema"
version = "0.1.0"
edition = "2021"
authors = ["tamasfe"]
keywords = ["web", "axum", "json"]
license = "MIT OR Apache-2.0"
description = "Request JSON schema validation for axum"

[dependencies]
aide = { version = "0.5.0", path = "../aide", optional = true, features = [
    "axum",
] }
async-trait = "0.1.57"
axum = "0.6.0-rc.1"
http = "0.2.8"
http-body = "0.4.5"
jsonschema = { version = "0.16.0", default-features = false }
schemars = "0.8.10"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tracing = "0.1.36"

[features]
default = ["aide"]
