[package]
name = "aide"
version = "0.1.0"
authors = ["tamasf97"]
edition = "2018"

[dependencies]
actix-web = { version = "3", optional = true }
aide-macros = { path = "../aide-macros" }
askama = { version = "0.10", optional = true }
linkme = "0.2"
schemars = { git = "https://github.com/tamasfe/schemars.git", branch = "master", features = ["impl_json_schema"] }
serde = "1"
serde_json = "1"

[dev-dependencies]
actix-web = "3"
anyhow = "1"

[features]
default = ["openapi-v3", "actix", "ui-redoc"]

actix = ["actix-web"]
openapi-v3 = []
ui-redoc = ["askama"]

[[example]]
name = "actix"
required-features = ["actix", "ui-redoc", "openapi-v3"]
